version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB
      MYSQL_USER: $DB
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  pg:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
